version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    user: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dev-journal
    ports:
      - "3000:3000"
    depends_on:
      - db